/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'hoon' at '15. 10. 16 오후 1:08' with Gradle 2.3
 *
 * @author hoon, @date 15. 10. 16 오후 1:08
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
